env:
  img_size: 224
  max_steps: 200
  action_delta: 0.05 #0.08
  init_with_pred_prob: 0.4 #0.7 # 使用预训练初始化
  init_box_jitter: 0.05    # 初始化时对边界框进行轻微扰动
  debug_log: false
  debug_log_interval: 50
  obs_cache_size: 1024
  observation_mode: false  # 调试 验证瓶颈

train:
  training_gpus: 1 #0
  algorithm: "PPO"    
  num_workers: 16    
  pin_rollout: true 
  fast_reset: true
  #total_timesteps: 20000000

  supervised_pretrain: true #true    # 是否启用监督预训练
  pretrain_epochs: 20 #40  6       # 监督预训练轮数
  pretrain_lr: 5e-5 #1e-4            # 预训练学习率
  pretrain_batch_size: 512      # 预训练 batch size
  init_ckpt: ""                 # 填 pth 路径则跳过预训直接 PPO
  apply_init_action_bias: false # 建议：加载 ckpt 时保持 false

  gamma: 0.99
  lam: 0.95
  clip_param: 0.2
  lr: 3e-4  #7e-5 
  n_steps: 256 #512
  batch_size: 2048 # 1536
  minibatch_size: 2048 #256 #128
  ppo_epochs: 4 #6 #10
  value_loss_coef: 0.5
  entropy_coef: 0.07 #0.05
  entropy_coef_final: 0.01
  stop_mask_steps: 8
  max_grad_norm: 0.8 # 0.5
  max_steps:  1000000 #8000000
  
  log_interval: 10
  save_interval: 20
  val_interval: 20
  val_eval_episodes: 64
  save_dir: "./Adacrop/logs"
  
nima:
  device_id: 1 #0
  use_dual_gpu: false               
  batch_size: 128 # 32          
  max_wait_time: 0.01
  cache_size: 10000
  queue_size: 2048
  weights_path: "./NIMA/weights/inception_resnet_weights.h5" #"./NIMA/weights/nima_inception_pytorch.pth"
  real_score_interval: 1 #5     
  scorer_type: gaic
  gaic_repo_dir: /ai/lzy/LiveCompose/Adacrop/GAIC
  gaic_ckpt: /ai/lzy/LiveCompose/Adacrop/GAIC/pretrained_models/GAIC-mobilenetv2-reddim16.pth
  gaic_backbone: mobilenetv2
  normalize_to_nima_scale: true

reward:
  # 基础惩罚
  no_op_penalty: 0.02
  boundary_penalty: 0.05

  # 重复访问/重复动作
  visit_penalty: 0.02
  repeat_penalty: 0.08
  max_repeat: 12

  # 回到上一步（解决 left/right 来回）
  backtrack_penalty: 0.20

  # stop shaping（鼓励接近 best 时停止）
  stop_early_step: 5
  stop_early_penalty: 0.2
  stop_close_best_eps1: 0.01
  stop_close_best_eps2: 0.03
  stop_close_best_eps3: 0.08
  stop_reward_eps1: 0.35
  stop_reward_eps2: 0.15
  stop_penalty_eps3: 0.10
  stop_penalty_far: 0.30
  stop_prev_clip: 0.2

  # same-action run penalty
  same_action_t1: 4
  same_action_t2: 6
  same_action_p1: 0.03
  same_action_p2: 0.08

  # oscillation penalty
  osc_window: 12
  osc_t1: 2
  osc_t2: 4
  osc_t3: 6
  osc_p1: 0.06
  osc_p2: 0.18
  osc_p3: 0.35

  # move/zoom bonus
  move_base: 0.05
  move_dist_scale: 0.25
  move_new_region_bonus: 0.05
  zoom_bonus: 0.06
  zoom_allow_drop: 0.01

  # size control
  area_target: 0.35
  area_weight: 0.15
  area_tolerance: 0.10

  # zoom_out restriction
  zoom_out_noop_penalty: 0.05
  zoom_out_area_max: 0.55
  zoom_out_area_penalty: 0.8

data:
  train_json: "./Adacrop/data/splits/train_mixed2.json"
  val_json:   "./Adacrop/data/splits/val_mixed.json"
  num_envs: 128 #96

export:
  onnx_opset: 13
  coreml_precision: "float16"